ambuda/views.py
import os
import random
from zipfile import ZipFile

from flask import (current_app as app, flash, redirect, render_template as
                   render, url_for, Blueprint)
from flask.ext.security import current_user
from flask.ext.security.decorators import roles_required
from flask.ext.uploads import configure_uploads, UploadSet, IMAGES
import sqlalchemy.exc

from ambuda.forms import ImagesForm, SegmentEditForm
from ambuda.models import *


images = UploadSet('img', IMAGES)
GET_POST = ['GET', 'POST']
STATUS = {}

# Since we're using the factory pattern, we have to bind our views to a
# blueprint.
site = Blueprint('site', __name__, template_folder='templates')


@site.context_processor
def upload_sets():
    return {
        'images': images,
        'Status': Status
    }

    # Helper functions
# ~~~~~~~~~~~~~~~~


def missing_project(slug):
    flash("Sorry, we couldn't find \"%s\"." % slug, 'error')
    return redirect(url_for('project_list'))


def get_project(slug):
    """Fetch a project.

    :param slug: the project slug
    """
    try:
        return Project.query.filter(Project.slug == slug).one()
    except sqlalchemy.exc.SQLAlchemyError:
        return None


def get_segment(project_id, id):
    """Fetch a segment.

    :param project_id:
    :param id:
    """
    try:
        return Segment.query.filter(Segment.id == id).one()
    except sqlalchemy.exc.SQLAlchemyError:
        return None


def random_segment(project_id):
    """Fetch a random segment from the project.

    :param project_id: the project ID
    """
    q = Segment.query.filter(Segment.project_id == project_id)
    count = q.count()
    return q.offset(random.randrange(count)).first()


# View functions
# ~~~~~~~~~~~~~~
@site.route('/')
def index():
    if current_user.is_authenticated():
        return render('index-user.html')
    else:
        return render('index-splash.html')


@site.route('/about')
def about():
    return render('about.html')


@site.route('/how-to/proofread')
def proofreading():
    return render('how-to/proofread.html')


@site.route('/projects/')
def project_list():
    projects = Project.query.all()
    return render('project_list.html', projects=projects)


@site.route('/projects/<slug>/')
def project(slug):
    _project = get_project(slug)
    if _project is None:
        return missing_project(slug)

    return render('project.html', project=_project)


@site.route('/projects/<slug>/edit/', methods=GET_POST)
@site.route('/projects/<slug>/edit/<int:id>', methods=GET_POST)
def segment_edit(slug, id=None):
    _project = get_project(slug)
    if _project is None:
        return missing_project(slug)

    if id is None:
        new_id = random_segment(_project.id).id
        return redirect(url_for('segment_edit', slug=slug, id=new_id))

    _segment = get_segment(_project.id, id)
    if _segment is None:
        return redirect(url_for('project', slug=slug))

    form = SegmentEditForm()
    if _segment.revisions:
        form.content.data = _segment.revisions[-1].content

    if form.validate_on_submit():
        # Create a new revision. `index` is populated automatically.
        new_status = Status.next(_segment.status)
        rev = Revision(
            content=form.content.data,
            status=new_status,
            segment_id=_segment.id
        )
        _segment.status = new_status
        _segment.revisions.append(rev)

        db.session.commit()
        flash('Saved!', 'success')

        # If marked as complete, show a new segment
        if form.complete.data:
            new_id = random_segment(_project.id).id
            return redirect(url_for('segment_edit', slug=slug, id=new_id))

    return render('segment.html', form=form,
                  project=_project,
                  segment=_segment)


@site.route('/projects/<slug>/upload', methods=['GET', 'POST'])
@roles_required('admin')
def upload_segments(slug):
    """
    Upload segments to the given project. Segments are bundled in a
    single zip file.

    :param slug: the project slug
    """
    _project = get_project(slug)
    if _project is None:
        return missing_project(slug)

    form = ImagesForm()
    if form.validate_on_submit():
        z = ZipFile(form.path.data)

        # Extract all images to <images>/<slug>
        dir_path = images.path(slug)
        z.extractall(dir_path)

        # Create `Segment` objects for each image.
        filenames = [os.path.join(slug, f) for f in z.namelist()]
        for name in filenames:
            db.session.add(Segment(
                image_path=name,
                project_id=_project.id,
                status=Status.proofreading_1
            ))
            db.session.commit()

        flash('Uploaded %s images.' % len(filenames))

    return render('upload-segments.html', form=form)

ambuda/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<h1>About</h1>

<h2 id="projects">Projects</h2>
<p>Many of the most popular Sanskrit texts have already been digitized. But there is still an enormous number of important and valuable texts that exist only as scans, if they've even been scanned at all. And there are hundreds of related texts &mdash; like translations, commentaries, and so on &mdash; that deserve our attention too.</p>

<h2 id="process">Process</h2>
<p>Instead of burdening a single person with an entire project, we split the project into hundreds of <dfn>fragments</dfn>. This has two main advantages:</p>

<ul>
    <li>It's easy to get started and contribute to a project.</li>
    <li>Multiple people can work on a project at the same time.</li>
</ul>

<p>This approach was first developed by <a href="http://pgdp.net">Distributed Proofreading</a>, but we've tried to simplify it here and make it easier for users to get started.</p>

<h2 id="results">Results</h2>
<p>Results are released under the most permissive license possible. Usually, this means that texts will be released into the public domain.</p>

{% endblock %}

ambuda/templates/index-splash.html
{% extends 'layout.html' %}
{% import 'macros.html' as macros %}

{% block title %}Ambuda{% endblock %}

{% macro read_more(anchor) %}
    <a href="{{ url_for('.about') }}#{{ anchor }}" class="btn btn-large">Read more &raquo;</a>
{% endmacro %}

{% block body %}
<div class="jumbotron">
    <h1>Ambuda</h1>
    <p class="lead">Digitize the Sanskrit world in just 5 minutes a day</p>
    <a href="{{ url_for('security.register') }}" class="btn btn-large btn-success">Sign up and start helping</a>
</div>

<div class="container">
<div class="row">
    <div class="span4">
        <h2>Projects</h2>
        <p>Important and uncommon texts in Sanskrit, English, and related languages. None of these texts have electronic versions available online.</p>
        {{ read_more('.projects') }}
    </div>

    <div class="span4">
        <h2>Process</h2>
        <p>Work on one page at a time. Do as much or as little as you like. Many hands make light work, and together, we can bring these texts into the 21st century.</p>
        {{ read_more('.process') }}
    </div>

    <div class="span4">
        <h2>Results</h2>
        <p>All results are released under the most permissive licenses possible, so that they can endure into future generations.</p>
        {{ read_more('.results') }}
    </div>
</div>
</div>
{% endblock %}

ambuda/templates/index-user.html
{% extends 'layout.html' %}
{% import 'macros.html' as macros %}

{% block title %}Index{% endblock %}

{% block style %}
    h2 {
        margin-top: 1em;
    }
    .btn-large {
        text-align: center;
    }
{% endblock %}

{% block content %}
<h1>What now?</h1>

<h2>1. <a href="{{ url_for('site.project_list') }}">Find a project</a> you want to work on</h2>
<p>Look over the <a href="{{ url_for('site.project_list') }}">full list of projects</a> and try to find a project you can work on. Some projects are easier than others.</p>

<h2>2. Learn <a href="{{ url_for('site.proofreading') }}">how to proofread</a></h2>
<p>These <a href="{{ url_for('site.proofreading') }}">basic guidelines</a> make sure that different pieces of a project are relatively consistent. Do your best to follow them, but don't worry about being exact.</p>

<h2>3. Start helping!</h2>
<p>With your help, we can make these texts more accessible than ever before and ensure that they survive for generations to come.</p>

{% endblock %}

ambuda/templates/layout.html
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <style>
      {% block style %}{% endblock %}
    </style>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-responsive.min.css') }}" />
    {% assets "all-css" %}<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />{% endassets %}

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone-min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/sanscript.js') }}"></script>
    {# <script type="text/javascript" src="{{ url_for('static', filename='js/markdown.js') }}"></script> #}
    {% assets "all-js" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
  </head>
  <body>
    <div id="wrap">
      <div class="container">
        <div class="masthead">
          <ul class="nav nav-pills pull-right">
            <li><a href="{{ url_for('site.project_list') }}">Projects</a></li>
            {% if current_user.has_role('admin') %}<li><a href="{{ url_for('admin.index') }}">Admin</a></li>{% endif %}
            <li>
            {% if current_user.is_authenticated() %}
            <ul class="nav nav-pills">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ current_user.email }}
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('security.logout') }}">Log out</a></li>
                </ul>
              </li>
            </ul>
            {% else %}
            <a href="{{ url_for('security.login') }}">Log in</a>
            {% endif %}
            </li>
          </ul>
          <h3 class="muted"><a href="{{ url_for('site.index') }}">Ambuda</a></h3>
        </div>
      </div>
      {% block body %}
        <hr />

        <div class="container">
          {% block flashed %}
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% for category, message in messages %}
              <div class="alert alert-{{ category }}">{{ message }}</div>
              {% endfor %}
            {% endwith %}
          {% endblock %}
          {% block content %}{% endblock %}
      </div>
      {% endblock %}
      <div id="push"></div>
    </div>
    <footer>
      <div class="container">
        Created by <a href="http://learnsanskrit.org">learnsanskrit.org</a>
      </div>
    </footer>
  </body>
</html>

ambuda/templates/macros.html
{# show a form field #}
{% macro show_field(field) %}
    {% set e = field.errors %}
    <div class="control-group{% if e %} error{% endif %}">
        {{ field.label(class='control-label') }}
        <div class="controls">
            {{ field }}
            {% if e %}
            <ul class="help-inline">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
{% endmacro %}

ambuda/templates/project.html
{% extends 'layout.html' %}
{% import 'macros.html' as m %}

{% macro progress_bar(p) %}
    {% set num_c = p.segments_with_status(Status.COMPLETE).count() %}
    {% set num_f = p.segments_with_status(Status.FORMATTING).count() %}
    {% set num_p = p.segments_with_status(Status.PROOFREADING).count() %}
    {% set total = num_p + num_f + num_c + 0.0 %}
    <div class="well">
        <h2>Stats</h2>
    <div class="progress">
        {% if total > 0 %}
        <div class="bar bar-success" style="width:{{ 100 * num_c / total}}%"></div>
        <div class="bar bar-warning" style="width:{{ 100 * num_f / total}}%"></div>
        <div class="bar bar-danger" style="width:{{ 100 * num_p / total}}%"></div>
        {% endif %}
    </div>
    <p>
        <span class="label label-success">{{ num_c }} complete</span>
        <span class="label label-warning">{{ num_f }} in formatting</span>
        <span class="label label-important">{{ num_p }} in proofreading</span>
    </p>
    </div>
{% endmacro %}

{% macro buttons(p) %}
    {% if current_user.can_edit and current_user.can_edit(p) %}
    <a href="{{ url_for('projectview.edit_view', id=p.id, url=url) }}" class="btn">Edit project</a>
    <a href="{{ url_for('site.upload_segments', slug=p.slug) }}" class="btn">Upload segments</a>
    {% endif %}
{% endmacro %}

{% block title %}{{ project.name }}{% endblock %}

{% set p = project %}
{% block content %}
<h1>{{ p.name }}</h1>

<div class="row">
    <div class="span8">
    <h2>Overview</h2>
        {{ p.introduction|markdown }}
        {{ buttons(p) }}
    </div>
    <div class="span4">
        {{ progress_bar(p) }}
    </div>
</div>

<h2>Before you start</h2>
<p class="alert alert-warning">Make sure you've read over the <a href="{{
        url_for('site.proofreading') }}">proofreading guidelines</a>. They're basic, but they're also very important!</p>

{% if p.instructions %}
<article id="instructions" class="well">
    {{ p.instructions|markdown }}
</article>
{% endif %}

<a href="{{ url_for('site.segment_edit', slug=p.slug) }}" class="btn btn-primary btn-large btn-block">Start helping</a>
{% endblock %}

ambuda/templates/project_list.html
{% extends 'layout.html' %}
{% import 'macros.html' as macros %}

{# --- Macros --- #}
{# Link to a project's edit page #}
{% macro project_options(p, user, url) %}
    {% if user.is_authenticated() %}
        <a href="{{ url_for('site.project', slug=p.slug) }}" class="btn btn-primary btn-large">Go to project &raquo;</a>
    {% else %}
        <a href="{{ url_for('security.register') }}" class="btn btn-primary">Sign up and start helping</a>
    {% endif %}
{% endmacro %}

{# Show a list of projects. #}
{% macro project_list(projects, user) %}
    {% for p in projects %}
    <section class="well">
        <h3>{{ p.name }} <span class="label label-important">Step 1: Proofreading</span></h3>
        {{ p.introduction|markdown }}
        {{ project_options(p, user, url_for('site.project_list')) }}
    </section>
    {% endfor %}
    </ul>
{% endmacro %}

{# --- Content --- #}
{% block title %}Index{% endblock %}

{% block content %}
<h1>Projects</h1>

{% if projects %}
{{ project_list(projects, current_user) }}
{% else %}
<p>No projects!</p>
{% endif %}
{% endblock %}

ambuda/templates/segment.html
{% extends 'layout.html' %}

{% macro another_page() %}
    <a href="{{ url_for('segment_edit', slug=project.slug) }}" class="btn">Show me another page</a>
{% endmacro %}

{% block title %}Index{% endblock %}

{% block content %}
<h1><a href="{{ url_for('project', slug=project.slug) }}">{{ project.name }}</a></h1>
<hr />

<form method="POST" action="{{ url_for('segment_edit', slug=project.slug, id=segment.id) }}">
    {{ form.csrf_token }}

    <h2>Image</h2>
    <div id="img-view"><img src="{{ images.url(segment.image_path) }}" /></div>

    <h2>Text</h2>
    {{ form.content(id='text-input', rows='30') }}

    {% set num_revisions = segment.revisions|length %}
    <p>
        {{ num_revisions }} revision{% if num_revisions != 1 %}s{% endif %}
        {% if num_revisions > 0 %}(last updated on {{ segment.revisions[-1].created }}){% endif %}
    </p>

    <div class="well">
        {% if segment.status == Status.proofreading_1 %}
        {{ form.in_progress(class='btn btn-primary') }}
        {{ another_page() }}
        {{ form.complete(class='btn btn-danger') }}
        {% elif segment.status == Status.proofreading_2 %}
        <p>Another user has marked this page as complete. Read through the text above <strong>carefully</strong> for any mistakes.</p>
        {{ another_page() }}
        {% endif %}
    </div>
</form>

{# <div id="preview" />

<script>
    $(function() {
        $('#text-input').keydown(function() {
            $('#preview').html(markdown.toHTML($(this).val()));
        });
    });
</script> #}
{% endblock %}

ambuda/templates/upload-segments.html
{% extends 'layout.html' %}
{% block content %}
<form enctype="multipart/form-data" method="POST" class="form-horizontal">
    {{ form.csrf_token }}
    {{ form.path.label }} {{ form.path }}
    <input type="submit" class="btn btn-primary" value="Submit"></input>
</form>
{% endblock %}